# baseURL
@baseURL = http://localhost:3000


# Create Accounts
POST {{ baseURL }}/accounts
Content-Type: application/json

{
                  sendername: 'tester',
                  recievername: '',
                  accountnumber: 1004032021,
                  amount: 2000,
                  naration: 'personal fund',
}


# Fund users accounts
POST {{ baseURL }}/accounts/funduserAccount
Content-Type: application/json

{
                  sendername: 'tester',
                  recievername: '',
                  accountnumber: 1004032021,
                  amount: 2000,
                  naration: 'personal fund',
}


# withDraw Funds
POST {{ baseURL }}/accounts/withDrawFunds/
Content-Type: application/json

{
     sendername:'tester',
     recievername:'williams',
     accountnumber: 1004032021,
     amount:500,
     naration:'removal',              
}
# FundsTransfer
POST {{ baseURL }}/accounts/FundsTransfer/
Content-Type: application/json
  {
   sendername: 'cole william',
   senderaccountnumber: '1004032021',
   recievername: 'william',
   recieveraccountnumber: '1004032021',
   amount: 5000,
   naration: 'test funding'
 }
